#ifndef _ASM_MEGADRIVE_H
#define _ASM_MEGADRIVE_H

#define MEGADRIVE_VDP_DATA	0xc00000
#define MEGADRIVE_VDP_CONTROL	0xc00004

#define MEGADRIVE_EVERDRIVE_MAILBOX		0xa130d0
#define MEGADRIVE_EVERDRIVE_MAILBOX_STAT	0xa130d2
#define MEGADRIVE_EVERDRIVE_MAPPER_CTRL		0xa130f0
#define MEGADRIVE_EVERDRIVE_MAPPER_CTRL_LED     (1 << 12)
#endif

